version: "3.3" # optional since v1.27.0
services:
  web:
    # build:
    #   context: ..
    #   dockerfile: ./odoo-dev-env/Dockerfile
    image: odoo12:v1
    ports:
      - "8070:8069"
    depends_on:
      - db
    volumes:
      - ../odoo:/home/odoo/app
      - odoo-data:/var/lib/odoo
      # - ./extra-addons:/home/odoo/app/custom-addons
      - ./config:/etc/odoo
    restart: always
    networks:
      - nk_o12_v1_pg14
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db_pg14_o12_v1:/var/lib/postgresql/data/pgdata
    restart: always
    networks:
      - nk_o12_v1_pg14

networks:
  nk_o12_v1_pg14:
    driver: bridge

volumes:
  odoo-data: {}
  db_pg14_o12_v1: {}
